### PR TITLE
table.create

### PR DESCRIPTION
**Pull request by Ukendio**
micro-optimization.

also changed temp variables such as new_table to copied for consistency

### CODE REVIEW

**Comment by sayhisam1** [comment]
Do you have any bmarks for this? Curious how much it speeds things up by.
Aside from that - consistency changes lgtm

**Comment by Ukendio** [comment]
I ran a simple test shallow copying an array of 1,000 elements using respective version of the Util module, a 10 times each. In the same test, I deep copied a 3-dimensional array a 10 times. 

And the consistent results proves that `{}` is marginally faster than table.create which disproves the aphorism about the slowness of dynamically resizing the array part of the hashtable, which conflicts with the motivation of this pull request.

I still haven't run the test for dictionaries, my conjectural knowledge on this is that there shouldn't be a difference. 

Therefore I will stop using table.create but I will still leave the consistency changes.

**Comment by Ukendio** [comment]
I ran a simple test shallow copying an array of 1,000 elements using respective version of the Util module, a 10 times each. In the same test, I deep copied a 3-dimensional array a 10 times. 

And the consistent results proves that `{}` is marginally faster than table.create which disproves the aphorism about the slowness of dynamically resizing the array part of the hashtable, which conflicts with the motivation of this pull request.

I still haven't run the test for dictionaries, my conjectural knowledge on this is that there shouldn't be a difference. 

Therefore I will stop using table.create and close this pr but I will probably make another PR that enforces the consistency changes

**Comment by sayhisam1** [comment]
interesting!

I guess `table.move` must already be pre-allocating space for the table internally (just like `table.create`)

Thanks for checking this!

**Pull request closed without merging**
